<?php

    /**
    * This file is part of BABOKI.COM
    * Module: slider
    *
    * @author       Błażej Skrzypniak <hi@skrzypniak.pl>
    * @link         https://baboki.com
    */

?>
<!-- slider -->
<link rel="stylesheet" href="<?= URL; ?>template/<?= VIEW ?>/lib/slider/css/owl.carousel.min.css">
<script src="<?= URL; ?>template/<?= VIEW ?>/lib/slider/js/owl.carousel.min.js"></script>
<script async src="<?= URL; ?>template/<?= VIEW ?>/lib/slider/js/owl.carousel.small.min.js"></script>
<script async src="<?= URL; ?>template/<?= VIEW ?>/lib/slider/js/owl.carousel.big.min.js"></script>