<?php

    /**
    * This file is part of BABOKI.COM
    * Module: lightbox
    *
    * @author       Błażej Skrzypniak <hi@skrzypniak.pl>
    * @link         https://baboki.com
    */
    
?>
<!-- lightbox -->
<link rel="stylesheet" href="<?php echo URL; ?>template/<?= VIEW ?>/lib/lightbox/css/lightbox.min.css">
<script async src="<?php echo URL; ?>template/<?= VIEW ?>/lib/lightbox/js/lightbox.min.js"></script>
<script async id="dsq-count-scr" src="//http-baboki-com-1.disqus.com/count.js"></script>