<?php

    /**
    * This file is part of BABOKI.COM
    * Module: back-to-top
    *
    * @author       Błażej Skrzypniak <hi@skrzypniak.pl>
    * @link         https://baboki.com
    */
    
?>
<!-- back-to-top -->
<a href="#" title="<?= $l['footer_7'] ?>" class="cd-top text--replace js-cd-top"><?= $l['footer_7'] ?></a>
<link rel="stylesheet" href="<?php echo URL; ?>template/<?= VIEW ?>/lib/back-to-top/css/back-to-top.css">
<script async src="<?php echo URL; ?>template/<?= VIEW ?>/lib/back-to-top/js/back-to-top.js"></script>