<?php

    /**
    * This file is part of BABOKI.COM
    * Module: preloader
    *
    * @author       Błażej Skrzypniak <hi@skrzypniak.pl>
    * @link         https://baboki.com
    */
    
?>
<!-- preloader -->
<div id="preloader"><div id="loader"></div></div>
<link href="<?= URL; ?>template/<?= VIEW ?>/lib/preloader/css/preloader.css" rel="stylesheet" />
<script async src="<?= URL; ?>template/<?= VIEW ?>/lib/preloader/js/pace.min.js"></script>
<script async src="<?= URL; ?>template/<?= VIEW ?>/lib/preloader/js/preloader.min.js"></script>